apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flamecraft-app-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flamecraft-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0   
      policies:
        - type: Pods
          value: 3                    
          periodSeconds: 60
        - type: Percent
          value: 100                   
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120  
      policies:
        - type: Pods
          value: 1                     
          periodSeconds: 60
        - type: Percent
          value: 50                   
          periodSeconds: 60